name: Formatting python code
    
on: 

  push:
    branches: ["sidebranch"]
  pull_request:
    types: opened
    branches: ["sidebranch"]

jobs:
    build: 
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: install dependecies
          run: |
            python -m pip install --upgrade pip
            pip install black
        - name: linting with black
          run: |
            black app/main.py
            black app/original.py
            black test_original.py   
        - name: Commit and push changes
          run: |
              git config --global user.email "kiriushkapolovko@gmail.com"
              git config --global user.name "p-kyrylo"
              git add .
              git commit -m "Apply Black formatting"
              git push
              