name: Testing python code with pytest

on: 

    push:
      branches: ["sidebranch"]
    pull_request:
      types: opened
      branches: ["sidebranch"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with: 
            python-version: "3.10"
        - name: Install dependencies
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-
        - if: ${{steps.cache-python.outputs.cache-hit != 'true'}}
          name: Install pip packages 
          continue-on-error: true
          run: | 
            python -m pip install --upgrade pip  
            pip install -r app/requirements.txt 
        - name: Get ffmpeg
          uses: FedericoCarboni/setup-ffmpeg@v3
          with:
           ffmpeg-version: release
           architecture: ''
           github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
        - name: Testing
          run: pytest test_original.py
        

